config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /pt-BR|en/ do
    root 'posts#index'

    get 'up' => 'rails/health#show', as: :rails_health_check

    resources :posts do
      resources :comments
      get '/page/:page', action: :index, on: :collection
    end

    post "sign_up", to: "users#create"
    get "sign_up", to: "users#new"

    get "profile", to: "users#show"
    get "profile/edit", to: "users#edit"
    patch "profile/edit", to: "users#update"

    get "password/edit", to: "users#edit_password"
    patch "password/update", to: "users#update_password"

    resources :passwords, only: [:create, :edit, :new, :update], param: :password_reset_token

    post "login", to: "sessions#create"
    delete "logout", to: "sessions#destroy"
    get "login", to: "sessions#new"
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  has_many :comments
  has_secure_password
  has_secure_token :remember_token

  MAILER_FROM_EMAIL = "no_reply@email.com"
  PASSWORD_RESET_TOKEN_EXPIRATION = 10.minutes

  before_save :downcase_email

  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }, presence: true, uniqueness: true

  def generate_password_reset_token
    signed_id expires_in: PASSWORD_RESET_TOKEN_EXPIRATION, purpose: :reset_password
  end

  def send_password_reset_email!
    password_reset_token = generate_password_reset_token
    UserMailer.password_reset(self, password_reset_token).deliver_now
  end

  private
  def downcase_email
    self.email = email.downcase
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout 'layouts/authentication', only: [:new]

  before_action :redirect_if_authenticated, only: %i[create new]
  before_action :authenticate!, except: %i[create new]

  def create
    @user = User.create(user_params.except(:old_password))

    if @user.save
      redirect_to login_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def new
    @user = User.new
  end

  def show
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user

    if @user.update(user_params.except(:password, :password_confirmation))
      redirect_to profile_path
      return
    end

    render :edit, status: :unprocessable_entity
  end

  def edit_password
    @user = current_user
  end

  def update_password
    unless params[:user][:old_password].present?
      flash.now[:alert] = 'Incorrect old password'
      render :edit_password, status: :forbidden
      return
    end

    @user = current_user

    unless @user.authenticate(params[:user][:old_password])
      flash.now[:alert] = 'Password doesn\'t matches'
      render :edit_password, status: :forbidden
      return
    end

    if @user.update(user_params.except(:old_password))
      redirect_to profile_path
    else
      render :edit_password, status: :unprocessable_entity
    end

  end

  private

  def user_params
    if params[:user][:old_password].present?
      return params.require(:user).permit(:username, :email, :password, :password_confirmation, :old_password)
    end
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<header class="container" style="height: 20rem">
  <div class="row gap-0 justify-content-center h-100 align-items-center">
    <h1 class="text-center text-uppercase"><%= @user.username %></h1>
    <p class="text-center"><%= t'.title' %></p>
  </div>
</header>

<main class="container col-3">
  <%= form_with model: @user, url: password_update_path, method: :patch do |form| %>
    <%= render "shared/form_errors", object: form.object %>

    <div class="form-floating mb-3">
      <%= form.text_field :username, required: true, class: "form-control", placeholder: t("user") %>
      <%= form.label :username, t("user") %>
    </div>
    <div class="form-floating mb-3">
      <%= form.email_field :email, required: true, class: "form-control", placeholder: t("email") %>
      <%= form.label :email, t('email') %>
    </div>

    <div class="mb-3 d-flex justify-content-end">
      <%= form.submit t(".save"), class: "btn btn-success" %>
    </div>
  <% end %>
</main>

app/views/users/edit_password.html.erb
<header class="container" style="height: 20rem">
  <div class="row gap-0 justify-content-center h-100 align-items-center">
    <h1 class="text-center text-uppercase"><%= @user.username %></h1>
    <p class="text-center"><%= t'.title' %></p>
  </div>
</header>

<main class="container col-3">
  <%= form_with model: @user, url: password_update_path, method: :patch do |form| %>

    <div class="form-floating">
      <%= render "shared/form_errors", object: form.object %>
    </div>

    <div class="form-floating mb-3">
      <%= form.password_field :old_password, required: true, class: "form-control", placeholder: t('old_password_field') %>
      <%= form.label :old_password, t('old_password_field') %>
    </div>

    <div class="form-floating mb-3">
      <%= form.password_field :password, required: true, class: "form-control", placeholder: t('password_field') %>
      <%= form.label :password, t('password_field') %>
    </div>

    <div class="form-floating mb-3">
      <%= form.password_field :password_confirmation, required: true, class: "form-control", placeholder: t('password_confirmation_field') %>
      <%= form.label :password_confirmation, t('password_confirmation_field') %>
    </div>

    <div class="mb-3 d-flex justify-content-end">
      <%= form.submit t('.save'), class: "btn btn-success" %>
    </div>
  <% end %>
</main>

app/views/users/new.html.erb
<h1 class="text-center"><%= t'.title' %></h1>

<%= form_with model: @user, url: sign_up_path do |form| %>

  <%= render "shared/form_errors", object: form.object %>

  <div class="form-floating mb-3">
    <%= form.text_field :username, required: true, class: "form-control", placeholder: t("user") %>
    <%= form.label :username, t("user") %>
  </div>
  <div class="form-floating mb-3">
    <%= form.email_field :email, required: true, class: "form-control", placeholder: t("email") %>
    <%= form.label :email, t("email") %>
  </div>
  <div class="form-floating mb-3">
    <%= form.password_field :password, required: true, class: "form-control", placeholder: t("password_field") %>
    <%= form.label :password, t("password_field") %>
  </div>
  <div class="form-floating mb-3">
    <%= form.password_field :password_confirmation, required: true, class: "form-control", placeholder: t("password_confirmation_field") %>
    <%= form.label :password_confirmation, t("password_confirmation_field") %>

  </div>

  <div class="d-flex justify-content-end">
    <%= form.submit t('.submit'), class: "btn btn-success" %>
  </div>



<% end %>

app/views/users/show.html.erb
<header class="container" style="height: 20rem">
  <div class="row gap-0 justify-content-center h-100 align-items-center">
    <h1 class="text-center text-uppercase"><%= @user.username %></h1>
    <p class="text-center"><%= t'.title' %></p>
  </div>
</header>

<main class="container col-3">

  <div class="form-floating mb-3">
    <input class="form-control-plaintext" id="floatingUsername" readonly value="<%= @user.username %>"/>
    <label for="floatingUsername"><%= t("user") %></label>
  </div>
  <div class="form-floating mb-3">
    <input class="form-control-plaintext" id="floatingEmail" readonly value="<%= @user.email %>"/>
    <label for="floatingEmail"><%= t("email") %></label>
  </div>
  <div class="d-flex justify-content-around">
    <%= link_to t(".change_info"), profile_edit_path, class: "btn btn-secondary" %>
    <%= link_to t(".change_pass"), password_edit_path, class: "btn btn-dark" %>

  </div>
</main>