config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /pt-BR|en/ do
    root 'posts#index'

    get 'up' => 'rails/health#show', as: :rails_health_check

    resources :posts do
      resources :comments
      get '/page/:page', action: :index, on: :collection
    end

    post "sign_up", to: "users#create"
    get "sign_up", to: "users#new"

    get "profile", to: "users#show"
    get "profile/edit", to: "users#edit"
    patch "profile/edit", to: "users#update"

    get "password/edit", to: "users#edit_password"
    patch "password/update", to: "users#update_password"

    resources :passwords, only: [:create, :edit, :new, :update], param: :password_reset_token

    post "login", to: "sessions#create"
    delete "logout", to: "sessions#destroy"
    get "login", to: "sessions#new"
  end
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
  belongs_to :user
  belongs_to :tag

  before_save :sanitize_content

  validates :title, presence: true
  validates :subtitle, presence: true
  validates :body, presence: true, length: { minimum: 10 }
  paginates_per 3

  private

  def sanitize_content
    self.body = Loofah.scrub_fragment(body, :prune).to_s
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate!, except: %i[index show]
  before_action :check_user, only: %i[edit destroy update]

  def index
    @tags = Tag.all

    if params[:tag_id].present?
      @posts = Post.where(tag_id: params[:tag_id]).order(created_at: :desc).page params[:page]
    else
      @posts = Post.order(created_at: :desc).page params[:page]
    end
  end

  def show
    @post = Post.find(params[:id])
    @username = User.find_by(id: @post.user_id).username

    @user_owner = user_owner?
  end

  def new
    @post = Post.new
    @tags = Tag.all
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save
      redirect_to @post
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @post = Post.find(params[:id])
    @tags = Tag.all
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to @post
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to root_path, status: :see_other
  end

  private

  def post_params
    params.require(:post).permit(:title, :subtitle, :body, :tag_id)
  end

  def check_user
    return if user_owner?

    redirect_to @post
  end

  def user_owner?
    @post = Post.find(params[:id])

    @user = current_user

    return false unless @user

    return true if @user.id == @post.user_id

    false
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with model: @post do |form| %>
  <div class="mb-3">
    <%= form.label :title, t("posts.post_title"), class: "form-label" %><br>
    <%= form.text_field :title, class:"form-control" %>
    <% if @post.present? %>
      <% @post.errors.full_messages_for(:title).each do |message| %>
        <div><%= message %></div>
      <% end %>
    <% end %>
  </div>
  <div class="mb-3">
    <%= form.label :subtitle, t("posts.post_subtitle"), class: "form-label" %><br>
    <%= form.text_field :subtitle, class: "form-control" %>
    <% if @post.present? %>
      <% @post.errors.full_messages_for(:subtitle).each do |message| %>
        <div><%= message %></div>
      <% end %>
    <% end %>
  </div>
  <div class="mb-3">
    <%= form.label :body, t("posts.post_body"), class: "form-label" %><br>
    <%= form.text_area :body, class:"form-control", style: "height: 25rem"  %>
    <% if @post.present? %>
      <% @post.errors.full_messages_for(:body).each do |message| %>
        <div><%= message %></div>
      <% end %>
    <% end %>
  </div>
  <div class="mb-3">
    <%= form.label :tag_id, t("posts.post_tag"), class: "form-label" %><br>
    <%= form.collection_select :tag_id, @tags, :id, :descryption, class: "form-select" %>
    <% if @post.present? %>
      <% @post.errors.full_messages_for(:tag_id).each do |message| %>
        <div><%= message %></div>
      <% end %>
    <% end %>
  </div>
  <div class="mb-3 d-flex flex-row-reverse">
    <%= form.submit submit_message, class:"btn btn-primary text-uppercase" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<header class="masthead">
  <div class="container position-relative px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="site-heading">
          <h1><%= t'.title' %></h1>
        </div>
      </div>
    </div>
  </div>
</header>

<div class="container container-lg px-4 px-lg-5">
  <div class="row gx-4 gx-lg-5 justify-content-center">
    <div class="col-md-10 col-lg-8 col-xl-7">
      <%= render "form", post: @post, submit_message: t('.save') %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<!-- Page Header-->
<header class="container" style="height: 20rem">
  <div class="row gap-0 justify-content-center h-100 align-items-center">
    <h1 class="text-center titles" style="font-size: 5rem">G<span class="titles text-bold text-success">Blog</span></h1>
    <span class="text-center"><%= t '.subtitle' %></span>
  </div>
</header>
<!-- Main Content-->
<main class="container px-4 px-lg-5">
  <article class="row gx-4 gx-lg-5 justify-content-center">
    <section class="col-md-10 col-lg-8 col-xl-7">

      <p class="d-inline-flex gap-1">
      <p class="text-primary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
        <%= t '.filter' %>
      </p>
      </p>
      <div class="collapse mb-3" , style="width: 200px;" id="collapseExample">
        <div class="card card-body w-100">
          <div class="d-flex w-100">
            <div class="w-100">
              <%= form_tag posts_path, method: :get do %>
                <% @tags.each do |tag| %>
                  <div class="form-check">
                    <%= radio_button_tag :tag_id, tag.id, params[:tag_id].to_i == tag.id, class: "form-check-input", type: "radio" %>
                    <%= label_tag "tag_id_#{tag.id}", tag.descryption, class: "form-check-label" %>
                  </div>
                <% end %>
                <%= submit_tag t('.filter'), class: "btn btn-primary mt-2 w-100 mb-2" %>
              <% end %>

              <% if params[:tag_id].present? %>
                <%= form_tag posts_path, method: :get, class: "mb-3" do %>
                  <%= submit_tag t('.clean_filter'), class: "btn btn-secondary mt-2 w-100" %>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>


      <!-- Post preview-->
      <% @posts.each do |p| %>
        <%= link_to(p) do %>
          <div class="card card-post-preview">
            <div class="card-body">
              <h5 class="card-title"><%= p.title %></h5>
              <% unless p.tag.nil? %>
                <div class="badge text-bg-danger bg-opacity-75 mb-2"><%= p.tag.descryption %></div>
              <% end %>
              <h6 class="card-subtitle mb-2 text-body-secondary"><%= p.subtitle %></h6>
              <p class="card-text">
                <%= t '.posted_by' %>
                <span>
                <%= p.user.username %>
              </span>
                <%= l(p.created_at, format: "%B %e, %Y").capitalize %>
              </p>
            </div>
          </div>
        <% end %>



        <!-- Divider-->
        <hr class="my-4"/>
      <% end %>

      <!-- Pager-->
      <div class="mb-3 d-flex flex-row-reverse">

        <%= paginate @posts %>

      </div>
    </section>
  </article>
</main>

app/views/posts/myposts.html.erb
<div class="posts_list">
    <%= render partial: "shared/back_arrow", locals: { image_name: 'mingcute--arrow-left-fill' } %>
    <%= button_to "Novo Post", post_path, method: :get, class: 'btn btn-primary' %>
    <% @user_posts.each do |post| %>
        <div class="card">
            <div class="post_title">
                <%= post.title %>
            </div>
            <div class="buttons_post"> 
                <%= button_to(image_tag('mdi--pencil.svg', style: 'width:30px;').html_safe, 
                    post_path + '/' + post.id.to_s,
                    method: :get,
                    class: 'button_fig',
                    style: 'width: 10%;') %>
                <%= button_to(image_tag('mdi--trash.svg', style: 'width:30px;').html_safe, 
                    post_path + '/' + post.id.to_s, 
                    method: :get,
                    class: 'button_fig',
                    style: 'width: 10%;') %>
            </div>
        </div>
    <% end %>
</div>

app/views/posts/new.html.erb
<header class="masthead">
  <div class="container position-relative px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="site-heading">
          <h1>Novo Post</h1>
        </div>
      </div>
    </div>
  </div>
</header>

<div class="container px-4 px-lg-5">

  <div class="row gx-4 gx-lg-5 justify-content-center">
    <div class="col-md-10 col-lg-8 col-xl-7">
      <%= render "form", post: @post, submit_message: t('.save') %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<header class="container" style="height: 20rem">
  <div class="row gap-0 justify-content-center h-100 align-items-center">
    <div class="text-center fw-bolder">
      <h1 class="text-break"><%= @post.title %></h1>
      <div class="text-success">
        <hr>
      </div>
      <h2 class="text-break fw-lighter text-secondary"><%= @post.subtitle %></h2>
    </div>

    <div class="text-center text-light-emphasis fst-italic">
      <%= t '.posted_by' %>
      <span><%= @username %></span> <%= t'.time_publication' %> <%= l(@post.created_at, format: "%B %e, %Y").capitalize %>
    </div>
  </div>
</header>
<!-- Post Content-->
<article class="mb-4">
  <div class="container container-lg px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">

      <div class="container">

        <div class="row mb-4 text-break">
          <%= simple_format(sanitize(@post.body, tags: %w(b strong em i)).html_safe) %>
        </div>

        <% unless @post.comments.empty? %>
          <div class="row mb-4">
            <h3 class="text-secondary"><%= t '.comments' %></h3>
            <%= render @post.comments %>
          </div>
        <% end %>
        <div class="row mb-4">
          <%= form_with model: [@post, @post.comments.build] do |form| %>
            <p class="mb-3">
              <%= form.label :body, t('.comment'), class: "form-label" %><br>
              <%= form.text_area :body, class: "form-control" %>
            </p>
            <div class="d-flex justify-content-end">
              <%= form.submit t('.comment'), class: "btn btn-outline-primary" %>
            </div>
          <% end %>
        </div>


        <% if @user_owner %>
          <div class="d-flex justify-content-between mb-3 gap-5">

            <%= link_to t('.edit'), edit_post_path(@post), class: "btn btn-primary flex-grow-1" %>


            <%= link_to t('.destroy'), post_path(@post), data: { turbo_method: :delete, turbo_confirm: "Tem certeza?" }, class: "btn btn-danger flex-grow-1" %>


          </div>
        <% end %>
      </div>
    </div>
  </div>
</article>