config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /pt-BR|en/ do
    root 'posts#index'

    get 'up' => 'rails/health#show', as: :rails_health_check

    resources :posts do
      resources :comments
      get '/page/:page', action: :index, on: :collection
    end

    post "sign_up", to: "users#create"
    get "sign_up", to: "users#new"

    get "profile", to: "users#show"
    get "profile/edit", to: "users#edit"
    patch "profile/edit", to: "users#update"

    get "password/edit", to: "users#edit_password"
    patch "password/update", to: "users#update_password"

    resources :passwords, only: [:create, :edit, :new, :update], param: :password_reset_token

    post "login", to: "sessions#create"
    delete "logout", to: "sessions#destroy"
    get "login", to: "sessions#new"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsBlog</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body>
<!-- Navigation-->

<nav class="navbar bg-success navbar-expand-lg mb-3" data-bs-theme="dark">
  <div class="container-fluid d-flex flex-justify-between">
    <%= link_to "Gblog", root_path, class: "navbar-brand" %>
    <div class="">
      <ul class="navbar-nav me-auto py-4 py-lg-0">

        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to t(".post"), new_post_path, class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to t(".profile"), profile_path, class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "Logout", logout_path, data: { turbo_method: :delete }, class: "nav-link" %>
          </li>

        <% else %>
          <li class="nav-item">
            <%= link_to t("layouts.sign_in"), login_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to t("layouts.sign_up"), sign_up_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

<div class="container-lg d-flex ">

  <div>
    <p><%= t('layouts.lang') %>: <%= locale %>

    </p>
    <p>
      <% unless locale == :en %>
        <%= link_to t('layouts.change_lang'), url_for(locale: :en), class: "text-primary" %>
      <% else %>
        <%= link_to t('layouts.change_lang'), url_for(locale: :'pt-BR'), class: "text-primary" %>
      <% end %>
    </p>

  </div>

</div>

<%= yield %>

app/views/layouts/authentication.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsBlog</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>
<body>
<main class=" px-4 px-lg-5 min-vh-100 d-flex justify-content-center align-items-center bg-success bg-opacity-50">
    <section class="col-md-8 col-lg-6 col-xl-4 border rounded p-5 bg-white shadow">
      <%= yield %>
    </section>
</main>
</body>